Document: vivid
Title: Debian vivid Manual
Author: <insert document author here>
Abstract: This manual describes what vivid is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vivid/vivid.sgml.gz

Format: postscript
Files: /usr/share/doc/vivid/vivid.ps.gz

Format: text
Files: /usr/share/doc/vivid/vivid.text.gz

Format: HTML
Index: /usr/share/doc/vivid/html/index.html
Files: /usr/share/doc/vivid/html/*.html
