#!/bin/sh

# Don't let them fail
# set -e

BASEPATH=$(pwd)

unit_test_dirs="
ansible_collections/ngine_io/cloudstack          # missing python3-units
ansible_collections/ansible/netcommon            # test broken
ansible_collections/netapp/ontap                 # missing netapp_lib
ansible_collections/netapp_eseries/santricity    # missing python3-units
ansible_collections/community/aws                # import broken
ansible_collections/community/vmware             # missing python3-units
ansible_collections/community/hrobot             # import broken
ansible_collections/community/general            # import broken
ansible_collections/community/skydive            # STDERR: WARNING: All targets skipped.
ansible_collections/junipernetworks/junos        # test broken
ansible_collections/dellemc/os6                  # import broken
ansible_collections/dellemc/os10                 # missing python3-units
ansible_collections/dellemc/os9                  # import broken
"

for i in $unit_test_dirs; do

  cd $i 2> /dev/null || continue

  echo "\n\n"
  echo "############################################################"
  echo "############################################################"
  echo "#### Running FLAKY tests in $i"
  echo "############################################################"
  echo "############################################################"

  /usr/bin/ansible-test units \
    --python-interpreter /usr/bin/python3 \
    --python 3.9 \
    --local

  cd $BASEPATH
done

exit 0
