#!/bin/sh

set -e

BASEPATH=$(pwd)

unit_test_dirs="
ansible_collections/amazon/aws
ansible_collections/ansible/posix
ansible_collections/ansible/windows
ansible_collections/arista/eos
ansible_collections/cisco/aci
ansible_collections/cisco/asa
ansible_collections/cisco/ios
ansible_collections/cisco/iosxr
ansible_collections/cisco/nso
ansible_collections/cisco/nxos
ansible_collections/community/crypto
ansible_collections/community/docker
ansible_collections/community/fortios
ansible_collections/community/google
ansible_collections/community/grafana
ansible_collections/community/kubevirt
ansible_collections/community/libvirt
ansible_collections/community/mysql
ansible_collections/community/network
ansible_collections/community/postgresql
ansible_collections/community/rabbitmq
ansible_collections/community/routeros
ansible_collections/community/windows
ansible_collections/f5networks/f5_modules
ansible_collections/frr/frr
ansible_collections/google/cloud
ansible_collections/mellanox/onyx
ansible_collections/netapp/aws
ansible_collections/netapp/elementsw
ansible_collections/netbox/netbox
ansible_collections/openvswitch/openvswitch
ansible_collections/vyos/vyos
"

for i in $unit_test_dirs; do

  cd $i 2> /dev/null || continue

  echo "\n\n"
  echo "############################################################"
  echo "############################################################"
  echo "#### Running tests in $i"
  echo "############################################################"
  echo "############################################################"

  /usr/bin/ansible-test units \
    --python-interpreter /usr/bin/python3 \
    --python 3.9 \
    --local

  cd $BASEPATH
done

exit 0
