#!/bin/sh

/usr/bin/ansible-test units \
  --python-interpreter /usr/bin/python3 \
  --python 3.9 \
  --local \
  --exclude test/units/cli/test_galaxy.py \
  --exclude test/units/galaxy/test_collection_install.py \
  --exclude test/units/modules/test_async_wrapper.py \
  --exclude test/units/utils/collection_loader/test_collection_loader.py \
