Document: kubectx
Title: Debian kubectx Manual
Author: <insert document author here>
Abstract: This manual describes what kubectx is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kubectx/kubectx.sgml.gz

Format: postscript
Files: /usr/share/doc/kubectx/kubectx.ps.gz

Format: text
Files: /usr/share/doc/kubectx/kubectx.text.gz

Format: HTML
Index: /usr/share/doc/kubectx/html/index.html
Files: /usr/share/doc/kubectx/html/*.html
