---
name: fonts-ubuntu-mono-nerd-font.yml
on:
  push:
    paths:
      - 'fonts-ubuntu-mono-nerd-font/**'
      - .github/workflows/fonts-ubuntu-mono-nerd-font.yml

env:
  DEBFULLNAME: Mario Finelli
  DEBEMAIL: ubuntu@mroml.com

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Detect ubuntu release codename
        run: echo "::set-output name=codename::$(./codename.sh)"
        id: ubuntu
      - name: Import signing key into local keyring
        run: echo -n "${{ secrets.SIGNING_KEY }}" | base64 -d | gpg --import
      - name: Install global packaging dependencies
        run: sudo apt install -y apt-file debhelper pbuilder ubuntu-dev-tools
      - name: Setup pbuilder
        run: pbuilder-dist ${{ steps.ubuntu.outputs.codename }} create
      - name: Test and then publish to PPA
        run: ./release.bash fonts-ubuntu-mono-nerd-font
      - name: Inspect package contents
        run: |
          find ~/pbuilder -not \( -path ~/pbuilder/aptcache -prune \) \
            -name '*.deb' -exec lesspipe {} \;

  port:
    name: Port ${{ matrix.ubuntu }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ubuntu: [jammy]
    env:
      DEBIAN_FRONTEND: noninteractive
    container: ubuntu:${{ matrix.ubuntu }}
    needs: [release]
    steps:
      - uses: actions/checkout@v3
      - name: Update and install dependencies
        run: |
          apt update -y
          apt upgrade -y
          apt install -y debhelper gnupg ubuntu-dev-tools
      - name: Import signing key into local keyring
        run: echo -n "${{ secrets.SIGNING_KEY }}" | base64 -d | gpg --import
      - name: Build the source package for the target and publish to PPA
        run: ./port.bash fonts-ubuntu-mono-nerd-font ${{ matrix.ubuntu }}
