---
name: gnome-shell-extension-espresso
on:
  push:
    paths:
      - gnome-shell-extension-espresso/**
      - .github/workflows/gnome-shell-extension-espresso.yml

env:
  DEBFULLNAME: Mario Finelli
  DEBEMAIL: ubuntu@mroml.com

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Detect ubuntu release codename
        run: echo "::set-output name=codename::$(./codename.sh)"
        id: ubuntu
      - name: Import signing key into local keyring
        run: echo -n "${{ secrets.SIGNING_KEY }}" | base64 -d | gpg --import
      - name: Run apt update before attempting to install dependencies
        run: sudo apt update && sudo apt upgrade -y
      - name: Install global packaging dependencies
        run: |
          sudo apt install -y apt-file brz-debian debhelper pbuilder \
            ubuntu-dev-tools
      - name: Install build dependencies
        run: |
          sudo apt install -y dh-sequence-gnome gobject-introspection
      - name: Setup pbuilder
        run: pbuilder-dist ${{ steps.ubuntu.outputs.codename }} create
      - name: Test and then publish to PPA
        run: ./release.bash gnome-shell-extension-espresso
        env:
          SKIP_UPLOAD: "true"
      - name: Inspect package contents
        run: |
          find ~/pbuilder -not \( -path ~/pbuilder/aptcache -prune \) \
            -name '*.deb' -exec lesspipe {} \;
      - uses: actions/upload-artifact@v4
        with:
          name: gnome-shell-extension-espresso
          path: |
            ~/pbuilder/${{ steps.ubuntu.outputs.codename}}_result/*.deb
