---
name: houmain-keymapper
on:
  push:
    paths:
      - 'houmain-keymapper/**'
      - .github/workflows/houmain-keymapper.yml

env:
  DEBFULLNAME: Mario Finelli
  DEBEMAIL: ubuntu@mroml.com

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Detect ubuntu release codename
        run: echo "::set-output name=codename::$(./codename.sh)"
        id: ubuntu
      - name: Import signing key into local keyring
        run: echo -n "${{ secrets.SIGNING_KEY }}" | base64 -d | gpg --import
      - name: Run apt update before attempting to install dependencies
        run: sudo apt update && sudo apt upgrade -y
      - name: Install global packaging dependencies
        run: sudo apt install -y apt-file debhelper pbuilder ubuntu-dev-tools
      - name: Install build dependencies
        run: |
          sudo apt install -y cmake git pkg-config libudev-dev \
            libusb-1.0-0-dev libx11-dev libdbus-1-dev libwayland-dev
      - name: Setup pbuilder
        run: pbuilder-dist ${{ steps.ubuntu.outputs.codename }} create
      - name: Test and then publish to PPA
        run: ./release.bash houmain-keymapper
      - name: Inspect package contents
        run: |
          find ~/pbuilder -not \( -path ~/pbuilder/aptcache -prune \) \
            -name '*.deb' -exec lesspipe {} \;
      - uses: actions/upload-artifact@v3
        with:
          name: houmain-keymapper
          path: |
            ~/pbuilder/${{ steps.ubuntu.outputs.codename}}_result/*.deb

  port:
    name: Port ${{ matrix.ubuntu }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ubuntu: [jammy]
    env:
      DEBIAN_FRONTEND: noninteractive
    container: ubuntu:${{ matrix.ubuntu }}
    needs: [release]
    steps:
      - uses: actions/checkout@v3
      - name: Update and install dependencies
        run: |
          apt update -y
          apt upgrade -y
          apt install -y debhelper gnupg ubuntu-dev-tools
      - name: Import signing key into local keyring
        run: echo -n "${{ secrets.SIGNING_KEY }}" | base64 -d | gpg --import
      - name: Install build dependencies
        run: |
          apt install -y cmake git pkg-config libudev-dev \
            libusb-1.0-0-dev libx11-dev libdbus-1-dev libwayland-dev
      - name: Build the source package for the target and publish to PPA
        run: ./port.bash houmain-keymapper ${{ matrix.ubuntu }}
