---
name: Release
on: push

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - run: echo "::set-output name=codename::$(grep UBUNTU_CODENAME /etc/os-release | awk -F= '{print $2}')"
        id: ubuntu
      - uses: actions/checkout@v2
      - run: echo -n "${{ secrets.SIGNING_KEY }}" | base64 -d | gpg --import
      - run: sudo apt install -y apt-file pbuilder ubuntu-dev-tools
      - name: Install build dependencies
        run: sudo apt install -y dh-python python3-all python3-pycryptodome python3-docutils python3-nose python3-packaging python3-passlib python3-straight.plugin
      - run: pbuilder-dist ${{ steps.ubuntu.outputs.codename }} create
      - run: ./build.bash ansible
